USE foodrecipe_db1;

-- Create the USERS table
CREATE TABLE IF NOT EXISTS USERS (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(50) NOT NULL UNIQUE,
    userPassword VARCHAR(255) NOT NULL
);

-- Create the RECIPES table
CREATE TABLE IF NOT EXISTS RECIPES (
    recipeID INT AUTO_INCREMENT PRIMARY KEY,
    recipeName VARCHAR(100) NOT NULL,
    recipeDescription TEXT NOT NULL,
    recipeImage VARCHAR(255) NOT NULL,
    recipeTime INT NOT NULL,
    recipeSteps TEXT NOT NULL,
    userName VARCHAR(50) NOT NULL,
    FOREIGN KEY (userName) REFERENCES USERS(userName) ON DELETE CASCADE
);

-- Create the INGREDIENTS table
CREATE TABLE IF NOT EXISTS INGREDIENTS (
    ingredientID INT AUTO_INCREMENT PRIMARY KEY,
    ingredientName VARCHAR(50) NOT NULL,
    ingredientUnit VARCHAR(50) NOT NULL
);

-- Create the BOOKMARKS table to link USERS to RECIPES they bookmarked
CREATE TABLE IF NOT EXISTS BOOKMARKS (
    bookmarkID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT,
    recipeID INT,
    FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
    FOREIGN KEY (recipeID) REFERENCES RECIPES(recipeID) ON DELETE CASCADE
);

-- Create the RECIPE_INGREDIENTS table to link RECIPES with INGREDIENTS and the quantity used
CREATE TABLE IF NOT EXISTS RECIPE_INGREDIENTS (
    recipeID INT,
    ingredientID INT,
    ingredientAmount DECIMAL(10, 2),
    PRIMARY KEY (recipeID, ingredientID),
    FOREIGN KEY (recipeID) REFERENCES RECIPES(recipeID) ON DELETE CASCADE,
    FOREIGN KEY (ingredientID) REFERENCES INGREDIENTS(ingredientID) ON DELETE CASCADE
);

